config/routes.rb
Rails.application.routes.draw do
  

  root 'restaurants#index'

  # devise_for :users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)

  devise_for :only_admin_users, {class_name: 'User'}.merge(ActiveAdmin::Devise.config)
  ActiveAdmin.routes(self)

 devise_for :users  
 
 resources :restaurants
 resources :dishes, only: [:show]

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter

  # def authorized?(action, subject = nil)
  #   user.admin?
  # end

  def authorized?(action, subject = nil)
    user.role == "admin"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord

	belongs_to :restaurant

	has_attached_file :image,                    
                    styles: {big: '300x300>', medium: '200x200>', thumb: '60x60>'},                   
                    default_url: '/images/:style/missing.png'
	validates_attachment_content_type :image, 
                    content_type: ['image/jpeg', 'image/jpg', 'image/gif', 'image/png']
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	
	has_many :dishes

	has_attached_file :image,                    
                    styles: { medium: '200x200>', thumb: '60x60>'},                   
                    default_url: '/images/:style/missing.png'
	validates_attachment_content_type :image, 
                    content_type: ['image/jpeg', 'image/jpg', 'image/gif', 'image/png']
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permited_parameters, if: :devise_controller?  
  protect_from_forgery with: :exception


  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_path
  end

    
  private  
  def configure_permited_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone, :adress])
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def show  	
  	@dish = Dish.find(params[:id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
  	@restaurants = Restaurant.all
  end

  def show
  	@restaurant = Restaurant.find(params[:id])
  	@dishes = Dish.where(restaurant_id: @restaurant.id)  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/dishes/show.html.erb
<div class="container">
	<div class="rest-thumb">
		<div class="photo">
			<div class="in">
				<%= image_tag @dish.restaurant.image.url(:thumb) %>
			</div>
		</div>
		<h3><%= link_to @dish.restaurant.title, restaurant_path %></h3>
	</div>
	<h1><%= @dish.title %></h1>	
	<div class="dish-show">
		<div class="dish-photo">			
			<%= image_tag @dish.image.url(:medium) %>
		</div>		
		<p class="dish-descr"><%= @dish.description %></p>
		<p class="price"><b>Цена, сом:</b> <%= @dish.price %></p>
	</div>	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodtractor</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <nav class="navbar navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Foodtractor', root_path, class: 'navbar-brand' %>
      </div>
      <div class="collapse navbar-collapse" id="navbar-collapse">

        <ul class="navbar-nav navbar-right">
          <% if user_signed_in? && current_user.role == 'admin' %>         
            <%= link_to "Admin Site", admin_root_path, class: 'btn btn-default navbar-btn' %>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-default navbar-btn' %>         

          <% elsif user_signed_in? %>
          <p class="navbar-text">

            Hello, <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'navbar-link' %>
          </p>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>               
                <li class="divider"></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          </ul>
          <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
          <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <%= yield %>
  
</body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
<h1>Заведения:</h1>
	<div class="restaurants row">
		<% @restaurants.each do |item| %>
			<div class="restaurant-item col-sm-4">
        <a href="<%= restaurant_path(item) %>">
          <div class="restaurant-logo">
            <%= image_tag item.image.url(:medium) %>
          </div>
          <h4><%= item.title %></h4>
        </a> 
      </div>         
		<% end %>
	</div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
	<h1><%= @restaurant.title %></h1>
	<div class="restaurant-info">
		<div class="restaurant-photo">
			<%= image_tag @restaurant.image.url(:medium) %>
		</div>
		<p class="restaurant-descr"><%= @restaurant.description %></p>
	</div>
	<h2>Меню:</h2>
	<div class="dishes">
		<% @dishes.each do |item| %>
			<div class="dish">
				<div class="dish-photo">
					<%= image_tag item.image.url(:medium) %>
				</div>
				<div class="dish-info">				
					<h4><%= item.title %></h4>
					<p><%= item.description %></p>
				</div>	
				<p class="price"><b>Цена, сом:</b> <%= item.price %></p>
				<p class="detail"><%= link_to "Подробнее", dish_path(item) %></p>				
			</div>
		<% end %>	
	</div>
</div>